# Generated by Django 4.2.7 on 2023-11-17 21:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type_code', models.CharField(max_length=15, unique=True, verbose_name='Account Type code')),
                ('tax', models.CharField(choices=[('ES', 'Exempt Sales 0%'), ('MP', 'MB - GST / RST on Purchasses 12%'), ('MS', 'MB - GST / RST on Sales 12%'), ('TE', 'Tax Exempt 0%'), ('TC', 'Tax on Consulting 8.25%'), ('TG', 'Tax on Goods 8.75%'), ('TP', 'Tax on Purchases 8.25%')], default='ES', max_length=2, verbose_name='Tax')),
            ],
            options={
                'verbose_name': 'Asset Account',
                'verbose_name_plural': 'Asset Accounts',
            },
        ),
        migrations.CreateModel(
            name='AssetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Asset Type')),
                ('depreciation_method', models.CharField(choices=[('ND', 'No Depreciation'), ('ST', 'Straight Line'), ('100', 'Diminishing Value 100'), ('150', 'Diminishing Value 150'), ('200', 'Diminishing Value 200'), ('FD', 'Full Depreciation')], default='ND', max_length=3, verbose_name='Depreciation Method')),
                ('averaging_method', models.CharField(choices=[('AD', 'Actual Days'), ('FM', 'Full Month')], default='AD', max_length=2, verbose_name='Averaging Method')),
                ('rate', models.FloatField(blank=True, null=True, verbose_name='Rate')),
                ('effective_life', models.PositiveIntegerField(blank=True, null=True, verbose_name='Effective Life')),
                ('accumulated_depreciation_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accumulated_depreciation_account', to='fixed_assets.assetaccount', verbose_name='Accumulated Depreciation Account')),
                ('asset_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_account', to='fixed_assets.assetaccount', verbose_name='Asset Account')),
                ('depreciation_expense_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depreciation_expense_account', to='fixed_assets.assetaccount', verbose_name='Depreciation Expense Account')),
            ],
            options={
                'verbose_name': 'Asset Type',
                'verbose_name_plural': 'Asset Types',
            },
        ),
        migrations.CreateModel(
            name='AssetSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start Date')),
                ('capital_gain_on_disposal', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capital_gain_on_disposal_setting', to='fixed_assets.assetaccount', verbose_name='Capital Gain on Disposal')),
                ('gain_on_disposal', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gain_on_disposal_setting', to='fixed_assets.assetaccount', verbose_name='Capital Gain on Disposal')),
                ('loss_on_disposal', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loss_on_disposal_setting', to='fixed_assets.assetaccount', verbose_name='Loss on Disposal')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='asset_setting_user', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Asset Setting',
                'verbose_name_plural': 'Asset Settings',
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Asset Name')),
                ('asset_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Asset Number')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='Purchase Date')),
                ('purchase_price', models.FloatField(blank=True, null=True, verbose_name='Purchase Price')),
                ('warranty_expiry', models.DateField(blank=True, null=True, verbose_name='Warranty Expiry')),
                ('serial_number', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Serial number')),
                ('region', models.CharField(choices=[('E', 'East Side'), ('N', 'North'), ('S', 'South'), ('W', 'West Coast')], default='E', max_length=1, verbose_name='Region')),
                ('description', models.TextField(blank=True, default=None, null=True, verbose_name='Description')),
                ('depreciation_start_date', models.DateField(blank=True, null=True, verbose_name='Depreciation Start Date')),
                ('cost_limit', models.FloatField(blank=True, null=True, verbose_name='Cost Limit')),
                ('residual_value', models.FloatField(blank=True, null=True, verbose_name='Residual Value')),
                ('depreciation_method', models.CharField(choices=[('ND', 'No Depreciation'), ('ST', 'Straight Line'), ('100', 'Diminishing Value 100'), ('150', 'Diminishing Value 150'), ('200', 'Diminishing Value 200'), ('FD', 'Full Depreciation')], default='ND', max_length=3, verbose_name='Depreciation Method')),
                ('averaging_method', models.CharField(choices=[('AD', 'Actual Days'), ('FM', 'Full Month')], default='AD', max_length=2, verbose_name='Averaging Method')),
                ('rate', models.FloatField(blank=True, null=True, verbose_name='Rate')),
                ('effective_life', models.PositiveIntegerField(blank=True, null=True, verbose_name='Effective Life')),
                ('asset_status', models.CharField(choices=[('RE', 'Registered'), ('DR', 'Draft'), ('DI', 'Disposed')], default='RE', max_length=2, verbose_name='Asset Status')),
                ('asset_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_asset_type', to='fixed_assets.assettype', verbose_name='Asset type')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_user', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Assets',
            },
        ),
    ]
