# Generated by Django 4.2.7 on 2023-11-17 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fixed_assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetsetting',
            name='gain_on_disposal',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gain_on_disposal_setting', to='fixed_assets.assetaccount', verbose_name='Gain on Disposal'),
        ),
    ]
