# Generated by Django 4.2.7 on 2023-11-17 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixed_assets', '0003_assettype_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assettype',
            name='effective_life',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='Effective Life'),
        ),
        migrations.AlterField(
            model_name='assettype',
            name='rate',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Rate'),
        ),
    ]
