# Generated by Django 4.2.7 on 2023-11-18 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixed_assets', '0004_alter_assettype_effective_life_alter_assettype_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='name',
            new_name='asset_name',
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_number',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Asset Number'),
        ),
    ]
