# Generated by Django 4.2.7 on 2023-11-21 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixed_assets', '0005_rename_name_asset_asset_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetaccount',
            name='account_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Account name'),
        ),
    ]
