# Generated by Django 4.2.7 on 2023-12-01 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixed_assets', '0007_calculateddepreciation'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculateddepreciation',
            name='book_date',
            field=models.DateField(blank=True, null=True, verbose_name='Book Date'),
        ),
    ]
