# Generated by Django 4.2.7 on 2023-12-01 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixed_assets', '0008_calculateddepreciation_book_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculateddepreciation',
            name='book_date',
        ),
        migrations.RemoveField(
            model_name='calculateddepreciation',
            name='book_value',
        ),
        migrations.AddField(
            model_name='calculateddepreciation',
            name='depreciation_date',
            field=models.DateField(blank=True, null=True, verbose_name='Depreciation Date'),
        ),
        migrations.AddField(
            model_name='calculateddepreciation',
            name='depreciation_of',
            field=models.FloatField(blank=True, null=True, verbose_name='Depreciation of'),
        ),
    ]
