# Generated by Django 4.2.7 on 2023-12-04 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixed_assets', '0009_remove_calculateddepreciation_book_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='book_value',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Book value'),
        ),
    ]
