# Generated by Django 4.2.7 on 2023-12-04 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fixed_assets', '0011_alter_asset_book_value'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='calculateddepreciation',
            unique_together={('asset', 'depreciation_date')},
        ),
    ]
