# Generated by Django 4.2.7 on 2023-12-13 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixed_assets', '0012_alter_calculateddepreciation_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetaccount',
            name='account_value',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Account Value'),
        ),
    ]
