# Generated by Django 4.2.8 on 2023-12-21 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fixed_assets', '0013_assetaccount_account_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisposedAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disposal_date', models.DateField(blank=True, null=True, verbose_name='Disposal Date')),
                ('gain_losses', models.FloatField(blank=True, null=True, verbose_name='Gain/losses')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disposed_asset_asset', to='fixed_assets.asset', verbose_name='Asset')),
                ('capital_gain_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capital_gain_account', to='fixed_assets.assetaccount', verbose_name='Capital gain Account')),
                ('gain_on_disposal_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gain_on_disposal_account', to='fixed_assets.assetaccount', verbose_name='Gain on disposal Account')),
                ('loss_on_disposal_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loss_on_disposal_account', to='fixed_assets.assetaccount', verbose_name='Loss on disposal Account')),
            ],
            options={
                'verbose_name': 'Disposed Asset',
                'verbose_name_plural': 'Disposed Assets',
            },
        ),
    ]
