# Generated by Django 4.2.8 on 2023-12-21 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fixed_assets', '0014_disposedasset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disposedasset',
            name='capital_gain_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='capital_gain_account', to='fixed_assets.assetaccount', verbose_name='Capital gain Account'),
        ),
        migrations.AlterField(
            model_name='disposedasset',
            name='gain_on_disposal_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gain_on_disposal_account', to='fixed_assets.assetaccount', verbose_name='Gain on disposal Account'),
        ),
        migrations.AlterField(
            model_name='disposedasset',
            name='loss_on_disposal_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loss_on_disposal_account', to='fixed_assets.assetaccount', verbose_name='Loss on disposal Account'),
        ),
    ]
