# Generated by Django 4.2.8 on 2023-12-21 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixed_assets', '0016_alter_disposedasset_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='disposedasset',
            name='disposal_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Disposal Price'),
        ),
    ]
